=============== iki =============
[INFO] [LOOP INITIALIZED] [loop = <ProactorEventLoop running=True closed=False debug=True>, name = None]
[INFO] [in if]
[INFO] [LOOP INITIALIZED] [loop = <ProactorEventLoop running=True closed=False debug=True>, name = None]
[INFO] [in if]
[INFO] [__step] [exc = None], [sent_from = '']
[INFO] [__step_run_and_handle_result],[exc = None]
======== FIRST.FIRST ===================
[INFO] [__step_run_and_handle_result] [result = <Future pending created at C:\Users\shaik\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py:448>], [getattr(result,'_asyncio_future_blocking',"NOT FOUND") = True]
[INFO] [__step_run_and_handle_result] [try-else] [result = <Future pending created at C:\Users\shaik\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py:448>],[result._asyncio_future_blocking = True]
[INFO] [__step_run_and_handle_result] [try-else] [blocking = True]
[INFO] [__step_run_and_handle_result] [add_done_call_back] [result =<Future pending created at C:\Users\shaik\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py:448>]
[INFO] [__step_run_and_handle_result] [_fut_waiter] [result =<Future pending cb=[Task.__wakeup()] created at C:\Users\shaik\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py:448>]
[INFO] [__step_run_and_handle_result] [_fut_waiter] [self._fut_waiter =<Future pending cb=[Task.__wakeup()] created at C:\Users\shaik\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py:448>]
[INFO] [__step] [exc = None], [sent_from = '']
[INFO] [__step_run_and_handle_result],[exc = None]
======== SECOND.FIRST ===================
[INFO] [__step_run_and_handle_result] [result = <Future pending created at C:\Users\shaik\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py:448>], [getattr(result,'_asyncio_future_blocking',"NOT FOUND") = True]
[INFO] [__step_run_and_handle_result] [try-else] [result = <Future pending created at C:\Users\shaik\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py:448>],[result._asyncio_future_blocking = True]
[INFO] [__step_run_and_handle_result] [try-else] [blocking = True]
[INFO] [__step_run_and_handle_result] [add_done_call_back] [result =<Future pending created at C:\Users\shaik\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py:448>]
[INFO] [__step_run_and_handle_result] [_fut_waiter] [result =<Future pending cb=[Task.__wakeup()] created at C:\Users\shaik\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py:448>]
[INFO] [__step_run_and_handle_result] [_fut_waiter] [self._fut_waiter =<Future pending cb=[Task.__wakeup()] created at C:\Users\shaik\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py:448>]
[INFO] [__wakeup] [future._state = 'FINISHED']
[INFO] [__step] [exc = None], [sent_from = '_wakeup._else']
[INFO] [__step_run_and_handle_result],[exc = None]
========= SECOND.SECOND =========================
[INFO] [__step_run_and_handle_result] [result = None], [getattr(result,'_asyncio_future_blocking',"NOT FOUND") = 'NOT FOUND']
Exception in callback Task.__wakeup(<Future finis...events.py:448>)
handle: <Handle Task.__wakeup(<Future finis...events.py:448>) created at C:\Users\shaik\AppData\Local\Programs\Python\Python312\Lib\asyncio\futures.py:315>
source_traceback: Object created at (most recent call last):
  File "C:\Users\shaik\AppData\Local\Programs\Python\Python312\Lib\asyncio\runners.py", line 194, in run
    return runner.run(main)
  File "C:\Users\shaik\AppData\Local\Programs\Python\Python312\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
  File "C:\Users\shaik\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 672, in run_until_complete
    self.run_forever()
  File "C:\Users\shaik\AppData\Local\Programs\Python\Python312\Lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\shaik\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 639, in run_forever
    self._run_once()
  File "C:\Users\shaik\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 1977, in _run_once
    handle._run()
  File "C:\Users\shaik\AppData\Local\Programs\Python\Python312\Lib\asyncio\events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\shaik\AppData\Local\Programs\Python\Python312\Lib\asyncio\futures.py", line 315, in _set_result_unless_cancelled
    fut.set_result(result)
Traceback (most recent call last):
  File "C:\Users\shaik\AppData\Local\Programs\Python\Python312\Lib\asyncio\events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "c:\Users\shaik\learning\p_l\async_l\tasks.py", line 336, in __wakeup
    self.__step(sent_from  = '_wakeup._else')
  File "c:\Users\shaik\learning\p_l\async_l\tasks.py", line 231, in __step
    self.__step_run_and_handle_result(exc)
  File "c:\Users\shaik\learning\p_l\async_l\tasks.py", line 267, in __step_run_and_handle_result
    print(f'\033[38;5;14m[INFO] [__step_run_and_handle_result] [try-else] [{result = !r }],[{result._asyncio_future_blocking = !r}]\033[0m')
                                                                                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute '_asyncio_future_blocking'
[INFO] [__wakeup] [future._state = 'FINISHED']
[INFO] [__step] [exc = None], [sent_from = '_wakeup._else']
[INFO] [__step_run_and_handle_result],[exc = None]
========= FIRST.SECOND =========================
[INFO] [__step_run_and_handle_result] [result = <Future pending created at C:\Users\shaik\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py:448>], [getattr(result,'_asyncio_future_blocking',"NOT FOUND") = True]
[INFO] [__step_run_and_handle_result] [try-else] [result = <Future pending created at C:\Users\shaik\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py:448>],[result._asyncio_future_blocking = True]
[INFO] [__step_run_and_handle_result] [try-else] [blocking = True]
[INFO] [__step_run_and_handle_result] [add_done_call_back] [result =<Future pending created at C:\Users\shaik\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py:448>]
[INFO] [__step_run_and_handle_result] [_fut_waiter] [result =<Future pending cb=[Task.__wakeup()] created at C:\Users\shaik\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py:448>]
[INFO] [__step_run_and_handle_result] [_fut_waiter] [self._fut_waiter =<Future pending cb=[Task.__wakeup()] created at C:\Users\shaik\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py:448>]
[INFO] [__wakeup] [future._state = 'FINISHED']
[INFO] [__step] [exc = None], [sent_from = '_wakeup._else']
[INFO] [__step_run_and_handle_result],[exc = None]
=========================== FIRST.THIRD =================
[INFO] [__step_run_and_handle_result] [result = <Future pending created at C:\Users\shaik\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py:448>], [getattr(result,'_asyncio_future_blocking',"NOT FOUND") = True]
[INFO] [__step_run_and_handle_result] [try-else] [result = <Future pending created at C:\Users\shaik\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py:448>],[result._asyncio_future_blocking = True]
[INFO] [__step_run_and_handle_result] [try-else] [blocking = True]
[INFO] [__step_run_and_handle_result] [add_done_call_back] [result =<Future pending created at C:\Users\shaik\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py:448>]
[INFO] [__step_run_and_handle_result] [_fut_waiter] [result =<Future pending cb=[Task.__wakeup()] created at C:\Users\shaik\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py:448>]
[INFO] [__step_run_and_handle_result] [_fut_waiter] [self._fut_waiter =<Future pending cb=[Task.__wakeup()] created at C:\Users\shaik\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py:448>]
[INFO] [__wakeup] [future._state = 'FINISHED']
[INFO] [__step] [exc = None], [sent_from = '_wakeup._else']
[INFO] [__step_run_and_handle_result],[exc = None]
========== END ===========
[INFO] [__step_run_and_handle_result] [exc.value = None]
