{"datetime": "2025-07-30 08:09:17 452530 PM", "level": "INFO", "func_name": "main", "lineno": 40, "filename": "understanding_tasks.py", "msg": "Main function calling"}
{"datetime": "2025-07-30 08:09:17 453639 PM", "level": "INFO", "func_name": "task_factory", "lineno": 412, "filename": "tasks.py", "msg": {"msg": "initalizing task", "vars": {"loop": "<ProactorEventLoop running=True closed=False debug=True>", "coro": "<coroutine object first at 0x000001CC14FE8100>", "task_name": "ASYNC-Custom-task-Task-1"}}}
{"datetime": "2025-07-30 08:09:17 453639 PM", "level": "INFO", "func_name": "__init__", "lineno": 48, "filename": "tasks.py", "msg": {"msg": "__init__ initalized"}}
{"datetime": "2025-07-30 08:09:17 454667 PM", "level": "INFO", "func_name": "__init__", "lineno": 76, "filename": "tasks.py", "msg": {"msg": "self.__step scheduled on EVENT_LOOP in __init__", "vars": {"task_name": "ASYNC-Custom-task-Task-1", "scheduler_type": "call_soon"}}}
{"datetime": "2025-07-30 08:09:17 455686 PM", "level": "INFO", "func_name": "__init__", "lineno": 79, "filename": "tasks.py", "msg": {"msg": "__init__ after scheduling __step on EVENT_LOOP using loop.call_soon", "vars": {"task_name": "ASYNC-Custom-task-Task-1", "scheduler_type": "call_soon"}}}
{"datetime": "2025-07-30 08:09:17 455686 PM", "level": "INFO", "func_name": "task_factory", "lineno": 412, "filename": "tasks.py", "msg": {"msg": "initalizing task", "vars": {"loop": "<ProactorEventLoop running=True closed=False debug=True>", "coro": "<coroutine object second at 0x000001CC14FE81C0>", "task_name": "ASYNC-Custom-task-Task-2"}}}
{"datetime": "2025-07-30 08:09:17 455686 PM", "level": "INFO", "func_name": "__init__", "lineno": 48, "filename": "tasks.py", "msg": {"msg": "__init__ initalized"}}
{"datetime": "2025-07-30 08:09:17 455686 PM", "level": "INFO", "func_name": "__init__", "lineno": 76, "filename": "tasks.py", "msg": {"msg": "self.__step scheduled on EVENT_LOOP in __init__", "vars": {"task_name": "ASYNC-Custom-task-Task-2", "scheduler_type": "call_soon"}}}
{"datetime": "2025-07-30 08:09:17 460958 PM", "level": "INFO", "func_name": "__init__", "lineno": 79, "filename": "tasks.py", "msg": {"msg": "__init__ after scheduling __step on EVENT_LOOP using loop.call_soon", "vars": {"task_name": "ASYNC-Custom-task-Task-2", "scheduler_type": "call_soon"}}}
{"datetime": "2025-07-30 08:09:17 460958 PM", "level": "INFO", "func_name": "__step", "lineno": 233, "filename": "tasks.py", "msg": {"msg": "Entered self.__step", "method_signature": "__step(self, exc = None)", "vars": {"task_name": "ASYNC-Custom-task-Task-1", "exc": "None", "sent_from": "'__init__'"}}}
{"datetime": "2025-07-30 08:09:17 460958 PM", "level": "INFO", "func_name": "__step", "lineno": 243, "filename": "tasks.py", "msg": {"msg": "will initalized self._fut_waiter value", "vars": {"task_name": "ASYNC-Custom-task-Task-1"}}}
{"datetime": "2025-07-30 08:09:17 460958 PM", "level": "INFO", "func_name": "__step", "lineno": 245, "filename": "tasks.py", "msg": {"msg": "initalized self._fut_waiter to None", "vars": {"task_name": "ASYNC-Custom-task-Task-1"}}}
{"datetime": "2025-07-30 08:09:17 460958 PM", "level": "INFO", "func_name": "__step", "lineno": 250, "filename": "tasks.py", "msg": {"msg": "`try` of try-finally in `self.__step`. Call to __step_run_and_handle_request in next line.", "vars": {"task_name": "ASYNC-Custom-task-Task-1"}}}
{"datetime": "2025-07-30 08:09:17 460958 PM", "level": "INFO", "func_name": "__step_run_and_handle_result", "lineno": 264, "filename": "tasks.py", "msg": {"msg": "__step_run_and_handle_request entered", "method_signature": "__step_run_and_handle_result(self, exc)", "vars": {"task_name": "ASYNC-Custom-task-Task-1", "exc": "None"}}}
{"datetime": "2025-07-30 08:09:17 460958 PM", "level": "INFO", "func_name": "__step_run_and_handle_result", "lineno": 271, "filename": "tasks.py", "msg": {"msg": "`__step_run_and_hanle_result` main try-except exc is None so `coro.send()` in next line.", "vars": {"task_name": "ASYNC-Custom-task-Task-1"}}}
{"datetime": "2025-07-30 08:09:17 460958 PM", "level": "INFO", "func_name": "first", "lineno": 11, "filename": "understanding_tasks.py", "msg": "======== FIRST.FIRST Will sleep next for .4 seconds ==================="}
{"datetime": "2025-07-30 08:09:17 460958 PM", "level": "INFO", "func_name": "__step_run_and_handle_result", "lineno": 274, "filename": "tasks.py", "msg": {"msg:": "__step_run_and_handle_result main try-except after `coro.send()`", "vars": {"task_name": "ASYNC-Custom-task-Task-1"}}}
{"datetime": "2025-07-30 08:09:17 460958 PM", "level": "INFO", "func_name": "__step_run_and_handle_result", "lineno": 312, "filename": "tasks.py", "msg": {"msg": "try-else in __step_run_and_handle_result", "vars": {"task_name": "ASYNC-Custom-task-Task-1", "future_name": "ASYNC-Custom-task-Task-1: name: 1", "result": "<Future pending created at C:\\Users\\shaik\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\asyncio\\base_events.py:448>", "is_asyncio_future_blocking": "getattr(result,\"_asyncio_future_blocking\", None)= True"}}}
{"datetime": "2025-07-30 08:09:17 460958 PM", "level": "INFO", "func_name": "__step_run_and_handle_result", "lineno": 315, "filename": "tasks.py", "msg": {"msg": "is_future blocking", "vars": {"task_name": "ASYNC-Custom-task-Task-1", "future_name": "ASYNC-Custom-task-Task-1: name: 1", "is_future_blocking": true}}}
{"datetime": "2025-07-30 08:09:17 460958 PM", "level": "INFO", "func_name": "__step_run_and_handle_result", "lineno": 332, "filename": "tasks.py", "msg": {"msg": "scheduling on EVENT_LOOP callback to fututre.add_done_call_back", "vars": {"task_name": "ASYNC-Custom-task-Task-1", "future_name": "ASYNC-Custom-task-Task-1: name: 1", "future_state": "PENDING", "result": "<Future pending created at C:\\Users\\shaik\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\asyncio\\base_events.py:448>", "scheduler_type": "call_soon"}}}
{"datetime": "2025-07-30 08:09:17 460958 PM", "level": "INFO", "func_name": "__step_run_and_handle_result", "lineno": 337, "filename": "tasks.py", "msg": {"msg": "After scheduling callbacks to fut. self._future_wait = result", "vars": {"task_name": "ASYNC-Custom-task-Task-1", "future_name": "ASYNC-Custom-task-Task-1: name: 1", "result": "<Future pending cb=[Task.__wakeup()] created at C:\\Users\\shaik\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\asyncio\\base_events.py:448>", "self._fut_waiter": null, "future_state": "PENDING", "future_callbacks_list(fut._callbacks)": [["__wakeup", "method"]]}}}
{"datetime": "2025-07-30 08:09:17 460958 PM", "level": "INFO", "func_name": "__step_run_and_handle_result", "lineno": 343, "filename": "tasks.py", "msg": {"msg": "self._fut_waiter set to result", "vars": {"task_name": "ASYNC-Custom-task-Task-1", "future_name": "ASYNC-Custom-task-Task-1: name: 1", "future_state": "PENDING", "self._fut_waiter": "<Future pending cb=[Task.__wakeup()] created at C:\\Users\\shaik\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\asyncio\\base_events.py:448>"}}}
{"datetime": "2025-07-30 08:09:17 460958 PM", "level": "INFO", "func_name": "__step_run_and_handle_result", "lineno": 376, "filename": "tasks.py", "msg": {"msg": "self finally set to None", "vars": {"task_name": "ASYNC-Custom-task-Task-1"}}}
{"datetime": "2025-07-30 08:09:17 460958 PM", "level": "INFO", "func_name": "__step", "lineno": 252, "filename": "tasks.py", "msg": {"msg": "`try` of try-finally in `self.__step`. After __step_run_and_handle_result", "vars": {"task_name": "ASYNC-Custom-task-Task-1"}}}
{"datetime": "2025-07-30 08:09:17 460958 PM", "level": "INFO", "func_name": "__step", "lineno": 257, "filename": "tasks.py", "msg": {"msg": "`finally` of try-finally in `self.__step`. Call to _leave_task next and then set self to None", "vars": {"task_name": "ASYNC-Custom-task-Task-1"}}}
{"datetime": "2025-07-30 08:09:17 460958 PM", "level": "INFO", "func_name": "__step", "lineno": 261, "filename": "tasks.py", "msg": {"msg": "`finally` of try-finally in `self.__step`.ASYNC-Custom-task-Task-1 set to none", "vars": {"task_name": "ASYNC-Custom-task-Task-1"}}}
{"datetime": "2025-07-30 08:09:17 460958 PM", "level": "INFO", "func_name": "__step", "lineno": 233, "filename": "tasks.py", "msg": {"msg": "Entered self.__step", "method_signature": "__step(self, exc = None)", "vars": {"task_name": "ASYNC-Custom-task-Task-2", "exc": "None", "sent_from": "'__init__'"}}}
{"datetime": "2025-07-30 08:09:17 460958 PM", "level": "INFO", "func_name": "__step", "lineno": 243, "filename": "tasks.py", "msg": {"msg": "will initalized self._fut_waiter value", "vars": {"task_name": "ASYNC-Custom-task-Task-2"}}}
{"datetime": "2025-07-30 08:09:17 460958 PM", "level": "INFO", "func_name": "__step", "lineno": 245, "filename": "tasks.py", "msg": {"msg": "initalized self._fut_waiter to None", "vars": {"task_name": "ASYNC-Custom-task-Task-2"}}}
{"datetime": "2025-07-30 08:09:17 460958 PM", "level": "INFO", "func_name": "__step", "lineno": 250, "filename": "tasks.py", "msg": {"msg": "`try` of try-finally in `self.__step`. Call to __step_run_and_handle_request in next line.", "vars": {"task_name": "ASYNC-Custom-task-Task-2"}}}
{"datetime": "2025-07-30 08:09:17 460958 PM", "level": "INFO", "func_name": "__step_run_and_handle_result", "lineno": 264, "filename": "tasks.py", "msg": {"msg": "__step_run_and_handle_request entered", "method_signature": "__step_run_and_handle_result(self, exc)", "vars": {"task_name": "ASYNC-Custom-task-Task-2", "exc": "None"}}}
{"datetime": "2025-07-30 08:09:17 476656 PM", "level": "INFO", "func_name": "__step_run_and_handle_result", "lineno": 271, "filename": "tasks.py", "msg": {"msg": "`__step_run_and_hanle_result` main try-except exc is None so `coro.send()` in next line.", "vars": {"task_name": "ASYNC-Custom-task-Task-2"}}}
{"datetime": "2025-07-30 08:09:17 476656 PM", "level": "INFO", "func_name": "second", "lineno": 20, "filename": "understanding_tasks.py", "msg": "======== SECOND.FIRST Will sleep for .5 seconds==================="}
{"datetime": "2025-07-30 08:09:17 476656 PM", "level": "INFO", "func_name": "__step_run_and_handle_result", "lineno": 274, "filename": "tasks.py", "msg": {"msg:": "__step_run_and_handle_result main try-except after `coro.send()`", "vars": {"task_name": "ASYNC-Custom-task-Task-2"}}}
{"datetime": "2025-07-30 08:09:17 476656 PM", "level": "INFO", "func_name": "__step_run_and_handle_result", "lineno": 312, "filename": "tasks.py", "msg": {"msg": "try-else in __step_run_and_handle_result", "vars": {"task_name": "ASYNC-Custom-task-Task-2", "future_name": "ASYNC-Custom-task-Task-2: name: 1", "result": "<Future pending created at C:\\Users\\shaik\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\asyncio\\base_events.py:448>", "is_asyncio_future_blocking": "getattr(result,\"_asyncio_future_blocking\", None)= True"}}}
{"datetime": "2025-07-30 08:09:17 476656 PM", "level": "INFO", "func_name": "__step_run_and_handle_result", "lineno": 315, "filename": "tasks.py", "msg": {"msg": "is_future blocking", "vars": {"task_name": "ASYNC-Custom-task-Task-2", "future_name": "ASYNC-Custom-task-Task-2: name: 1", "is_future_blocking": true}}}
{"datetime": "2025-07-30 08:09:17 476656 PM", "level": "INFO", "func_name": "__step_run_and_handle_result", "lineno": 332, "filename": "tasks.py", "msg": {"msg": "scheduling on EVENT_LOOP callback to fututre.add_done_call_back", "vars": {"task_name": "ASYNC-Custom-task-Task-2", "future_name": "ASYNC-Custom-task-Task-2: name: 1", "future_state": "PENDING", "result": "<Future pending created at C:\\Users\\shaik\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\asyncio\\base_events.py:448>", "scheduler_type": "call_soon"}}}
{"datetime": "2025-07-30 08:09:17 476656 PM", "level": "INFO", "func_name": "__step_run_and_handle_result", "lineno": 337, "filename": "tasks.py", "msg": {"msg": "After scheduling callbacks to fut. self._future_wait = result", "vars": {"task_name": "ASYNC-Custom-task-Task-2", "future_name": "ASYNC-Custom-task-Task-2: name: 1", "result": "<Future pending cb=[Task.__wakeup()] created at C:\\Users\\shaik\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\asyncio\\base_events.py:448>", "self._fut_waiter": null, "future_state": "PENDING", "future_callbacks_list(fut._callbacks)": [["__wakeup", "method"]]}}}
{"datetime": "2025-07-30 08:09:17 476656 PM", "level": "INFO", "func_name": "__step_run_and_handle_result", "lineno": 343, "filename": "tasks.py", "msg": {"msg": "self._fut_waiter set to result", "vars": {"task_name": "ASYNC-Custom-task-Task-2", "future_name": "ASYNC-Custom-task-Task-2: name: 1", "future_state": "PENDING", "self._fut_waiter": "<Future pending cb=[Task.__wakeup()] created at C:\\Users\\shaik\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\asyncio\\base_events.py:448>"}}}
{"datetime": "2025-07-30 08:09:17 476656 PM", "level": "INFO", "func_name": "__step_run_and_handle_result", "lineno": 376, "filename": "tasks.py", "msg": {"msg": "self finally set to None", "vars": {"task_name": "ASYNC-Custom-task-Task-2"}}}
{"datetime": "2025-07-30 08:09:17 476656 PM", "level": "INFO", "func_name": "__step", "lineno": 252, "filename": "tasks.py", "msg": {"msg": "`try` of try-finally in `self.__step`. After __step_run_and_handle_result", "vars": {"task_name": "ASYNC-Custom-task-Task-2"}}}
{"datetime": "2025-07-30 08:09:17 476656 PM", "level": "INFO", "func_name": "__step", "lineno": 257, "filename": "tasks.py", "msg": {"msg": "`finally` of try-finally in `self.__step`. Call to _leave_task next and then set self to None", "vars": {"task_name": "ASYNC-Custom-task-Task-2"}}}
{"datetime": "2025-07-30 08:09:17 481911 PM", "level": "INFO", "func_name": "__step", "lineno": 261, "filename": "tasks.py", "msg": {"msg": "`finally` of try-finally in `self.__step`.ASYNC-Custom-task-Task-2 set to none", "vars": {"task_name": "ASYNC-Custom-task-Task-2"}}}
{"datetime": "2025-07-30 08:09:17 990047 PM", "level": "INFO", "func_name": "__wakeup", "lineno": 381, "filename": "tasks.py", "msg": {"msg": "__wakeup entered", "vars": {"task_name": "ASYNC-Custom-task-Task-2", "future_name": "ASYNC-Custom-task-Task-2: name: 1", "future_state": "FINISHED"}}}
{"datetime": "2025-07-30 08:09:17 992066 PM", "level": "INFO", "func_name": "__wakeup", "lineno": 384, "filename": "tasks.py", "msg": {"msg": "will call future.result()", "vars": {"task_name": "ASYNC-Custom-task-Task-2", "future_name": "ASYNC-Custom-task-Task-2: name: 1"}}}
{"datetime": "2025-07-30 08:09:17 992066 PM", "level": "INFO", "func_name": "__wakeup", "lineno": 386, "filename": "tasks.py", "msg": {"msg": "__wakeup after future.result()", "vars": {"task_name": "ASYNC-Custom-task-Task-2", "future_name": "ASYNC-Custom-task-Task-2: name: 1", "future._state": "FINISHED"}}}
{"datetime": "2025-07-30 08:09:17 992066 PM", "level": "INFO", "func_name": "__wakeup", "lineno": 402, "filename": "tasks.py", "msg": {"msg": "__wakeup faced no exception when it called future.result()(ASYNC-Custom-task-Task-2: name: 1). calling again __step with no exc. I guess StopIteration will be raised", "vars": {"task_name": "ASYNC-Custom-task-Task-2", "future_name": "ASYNC-Custom-task-Task-2: name: 1"}}}
{"datetime": "2025-07-30 08:09:17 992066 PM", "level": "INFO", "func_name": "__step", "lineno": 233, "filename": "tasks.py", "msg": {"msg": "Entered self.__step", "method_signature": "__step(self, exc = None)", "vars": {"task_name": "ASYNC-Custom-task-Task-2", "exc": "None", "sent_from": "'_wakeup._else'"}}}
{"datetime": "2025-07-30 08:09:17 992066 PM", "level": "INFO", "func_name": "__step", "lineno": 243, "filename": "tasks.py", "msg": {"msg": "will initalized self._fut_waiter value", "vars": {"task_name": "ASYNC-Custom-task-Task-2"}}}
{"datetime": "2025-07-30 08:09:17 992066 PM", "level": "INFO", "func_name": "__step", "lineno": 245, "filename": "tasks.py", "msg": {"msg": "initalized self._fut_waiter to None", "vars": {"task_name": "ASYNC-Custom-task-Task-2"}}}
{"datetime": "2025-07-30 08:09:17 992066 PM", "level": "INFO", "func_name": "__step", "lineno": 250, "filename": "tasks.py", "msg": {"msg": "`try` of try-finally in `self.__step`. Call to __step_run_and_handle_request in next line.", "vars": {"task_name": "ASYNC-Custom-task-Task-2"}}}
{"datetime": "2025-07-30 08:09:17 992066 PM", "level": "INFO", "func_name": "__step_run_and_handle_result", "lineno": 264, "filename": "tasks.py", "msg": {"msg": "__step_run_and_handle_request entered", "method_signature": "__step_run_and_handle_result(self, exc)", "vars": {"task_name": "ASYNC-Custom-task-Task-2", "exc": "None"}}}
{"datetime": "2025-07-30 08:09:17 992066 PM", "level": "INFO", "func_name": "__step_run_and_handle_result", "lineno": 271, "filename": "tasks.py", "msg": {"msg": "`__step_run_and_hanle_result` main try-except exc is None so `coro.send()` in next line.", "vars": {"task_name": "ASYNC-Custom-task-Task-2"}}}
{"datetime": "2025-07-30 08:09:17 992066 PM", "level": "INFO", "func_name": "second", "lineno": 22, "filename": "understanding_tasks.py", "msg": "========= SECOND.SECOND Will sleep for 0 second========================="}
{"datetime": "2025-07-30 08:09:17 992066 PM", "level": "INFO", "func_name": "__step_run_and_handle_result", "lineno": 274, "filename": "tasks.py", "msg": {"msg:": "__step_run_and_handle_result main try-except after `coro.send()`", "vars": {"task_name": "ASYNC-Custom-task-Task-2"}}}
{"datetime": "2025-07-30 08:09:17 992066 PM", "level": "INFO", "func_name": "__step_run_and_handle_result", "lineno": 312, "filename": "tasks.py", "msg": {"msg": "try-else in __step_run_and_handle_result", "vars": {"task_name": "ASYNC-Custom-task-Task-2", "future_name": null, "result": "None", "is_asyncio_future_blocking": "getattr(result,\"_asyncio_future_blocking\", None)= None"}}}
{"datetime": "2025-07-30 08:09:18 005904 PM", "level": "INFO", "func_name": "__step_run_and_handle_result", "lineno": 315, "filename": "tasks.py", "msg": {"msg": "is_future blocking", "vars": {"task_name": "ASYNC-Custom-task-Task-2", "future_name": null, "is_future_blocking": null}}}
{"datetime": "2025-07-30 08:09:18 005904 PM", "level": "INFO", "func_name": "__step_run_and_handle_result", "lineno": 360, "filename": "tasks.py", "msg": {"msg": "result is None. Scheduling on EVENT_LOOP self.__step", "vars": {"task_name": "ASYNC-Custom-task-Task-2", "future_name": "No future", "scheduler_type": "call_soon"}}}
{"datetime": "2025-07-30 08:09:18 005904 PM", "level": "INFO", "func_name": "__step_run_and_handle_result", "lineno": 376, "filename": "tasks.py", "msg": {"msg": "self finally set to None", "vars": {"task_name": "ASYNC-Custom-task-Task-2"}}}
{"datetime": "2025-07-30 08:09:18 005904 PM", "level": "INFO", "func_name": "__step", "lineno": 252, "filename": "tasks.py", "msg": {"msg": "`try` of try-finally in `self.__step`. After __step_run_and_handle_result", "vars": {"task_name": "ASYNC-Custom-task-Task-2"}}}
{"datetime": "2025-07-30 08:09:18 005904 PM", "level": "INFO", "func_name": "__step", "lineno": 257, "filename": "tasks.py", "msg": {"msg": "`finally` of try-finally in `self.__step`. Call to _leave_task next and then set self to None", "vars": {"task_name": "ASYNC-Custom-task-Task-2"}}}
{"datetime": "2025-07-30 08:09:18 005904 PM", "level": "INFO", "func_name": "__step", "lineno": 261, "filename": "tasks.py", "msg": {"msg": "`finally` of try-finally in `self.__step`.ASYNC-Custom-task-Task-2 set to none", "vars": {"task_name": "ASYNC-Custom-task-Task-2"}}}
{"datetime": "2025-07-30 08:09:18 005904 PM", "level": "INFO", "func_name": "__wakeup", "lineno": 405, "filename": "tasks.py", "msg": {"msg": "end of __wakeup. set self = None", "vars": {"task_name": "ASYNC-Custom-task-Task-2", "future_name": "ASYNC-Custom-task-Task-2: name: 1"}}}
{"datetime": "2025-07-30 08:09:18 005904 PM", "level": "INFO", "func_name": "__step", "lineno": 233, "filename": "tasks.py", "msg": {"msg": "Entered self.__step", "method_signature": "__step(self, exc = None)", "vars": {"task_name": "ASYNC-Custom-task-Task-2", "exc": "None", "sent_from": "'__step_run_and_handle_result'"}}}
{"datetime": "2025-07-30 08:09:18 005904 PM", "level": "INFO", "func_name": "__step", "lineno": 243, "filename": "tasks.py", "msg": {"msg": "will initalized self._fut_waiter value", "vars": {"task_name": "ASYNC-Custom-task-Task-2"}}}
{"datetime": "2025-07-30 08:09:18 005904 PM", "level": "INFO", "func_name": "__step", "lineno": 245, "filename": "tasks.py", "msg": {"msg": "initalized self._fut_waiter to None", "vars": {"task_name": "ASYNC-Custom-task-Task-2"}}}
{"datetime": "2025-07-30 08:09:18 005904 PM", "level": "INFO", "func_name": "__step", "lineno": 250, "filename": "tasks.py", "msg": {"msg": "`try` of try-finally in `self.__step`. Call to __step_run_and_handle_request in next line.", "vars": {"task_name": "ASYNC-Custom-task-Task-2"}}}
{"datetime": "2025-07-30 08:09:18 005904 PM", "level": "INFO", "func_name": "__step_run_and_handle_result", "lineno": 264, "filename": "tasks.py", "msg": {"msg": "__step_run_and_handle_request entered", "method_signature": "__step_run_and_handle_result(self, exc)", "vars": {"task_name": "ASYNC-Custom-task-Task-2", "exc": "None"}}}
{"datetime": "2025-07-30 08:09:18 005904 PM", "level": "INFO", "func_name": "__step_run_and_handle_result", "lineno": 271, "filename": "tasks.py", "msg": {"msg": "`__step_run_and_hanle_result` main try-except exc is None so `coro.send()` in next line.", "vars": {"task_name": "ASYNC-Custom-task-Task-2"}}}
{"datetime": "2025-07-30 08:09:18 005904 PM", "level": "INFO", "func_name": "second", "lineno": 24, "filename": "understanding_tasks.py", "msg": "=========================== SECOND.THIRD No sleep================="}
{"datetime": "2025-07-30 08:09:18 005904 PM", "level": "INFO", "func_name": "second", "lineno": 26, "filename": "understanding_tasks.py", "msg": "========== END ==========="}
{"datetime": "2025-07-30 08:09:18 005904 PM", "level": "INFO", "func_name": "__step_run_and_handle_result", "lineno": 284, "filename": "tasks.py", "msg": {"msg": "StopIteration exception encountered.", "vars": {"task_name": "ASYNC-Custom-task-Task-2", "future_name": "NO_AWAITABLE"}}}
{"datetime": "2025-07-30 08:09:18 005904 PM", "level": "INFO", "func_name": "__step_run_and_handle_result", "lineno": 293, "filename": "tasks.py", "msg": {"msg": "__step_run_and_handle_result StopIteration encountered but the task is not cancelled.", "vars": {"task_name": "ASYNC-Custom-task-Task-2", "exc.value": "None"}}}
{"datetime": "2025-07-30 08:09:18 005904 PM", "level": "INFO", "func_name": "__step_run_and_handle_result", "lineno": 296, "filename": "tasks.py", "msg": {"msg": "super().set_result(exc.value)", "vars": {"task_name": "ASYNC-Custom-task-Task-2"}}}
{"datetime": "2025-07-30 08:09:18 005904 PM", "level": "INFO", "func_name": "__step_run_and_handle_result", "lineno": 376, "filename": "tasks.py", "msg": {"msg": "self finally set to None", "vars": {"task_name": "ASYNC-Custom-task-Task-2"}}}
{"datetime": "2025-07-30 08:09:18 005904 PM", "level": "INFO", "func_name": "__step", "lineno": 252, "filename": "tasks.py", "msg": {"msg": "`try` of try-finally in `self.__step`. After __step_run_and_handle_result", "vars": {"task_name": "ASYNC-Custom-task-Task-2"}}}
{"datetime": "2025-07-30 08:09:18 005904 PM", "level": "INFO", "func_name": "__step", "lineno": 257, "filename": "tasks.py", "msg": {"msg": "`finally` of try-finally in `self.__step`. Call to _leave_task next and then set self to None", "vars": {"task_name": "ASYNC-Custom-task-Task-2"}}}
{"datetime": "2025-07-30 08:09:18 005904 PM", "level": "INFO", "func_name": "__step", "lineno": 261, "filename": "tasks.py", "msg": {"msg": "`finally` of try-finally in `self.__step`.ASYNC-Custom-task-Task-2 set to none", "vars": {"task_name": "ASYNC-Custom-task-Task-2"}}}
{"datetime": "2025-07-30 08:09:21 468422 PM", "level": "INFO", "func_name": "__wakeup", "lineno": 381, "filename": "tasks.py", "msg": {"msg": "__wakeup entered", "vars": {"task_name": "ASYNC-Custom-task-Task-1", "future_name": "ASYNC-Custom-task-Task-1: name: 1", "future_state": "FINISHED"}}}
{"datetime": "2025-07-30 08:09:21 468422 PM", "level": "INFO", "func_name": "__wakeup", "lineno": 384, "filename": "tasks.py", "msg": {"msg": "will call future.result()", "vars": {"task_name": "ASYNC-Custom-task-Task-1", "future_name": "ASYNC-Custom-task-Task-1: name: 1"}}}
{"datetime": "2025-07-30 08:09:21 468422 PM", "level": "INFO", "func_name": "__wakeup", "lineno": 386, "filename": "tasks.py", "msg": {"msg": "__wakeup after future.result()", "vars": {"task_name": "ASYNC-Custom-task-Task-1", "future_name": "ASYNC-Custom-task-Task-1: name: 1", "future._state": "FINISHED"}}}
{"datetime": "2025-07-30 08:09:21 468422 PM", "level": "INFO", "func_name": "__wakeup", "lineno": 402, "filename": "tasks.py", "msg": {"msg": "__wakeup faced no exception when it called future.result()(ASYNC-Custom-task-Task-1: name: 1). calling again __step with no exc. I guess StopIteration will be raised", "vars": {"task_name": "ASYNC-Custom-task-Task-1", "future_name": "ASYNC-Custom-task-Task-1: name: 1"}}}
{"datetime": "2025-07-30 08:09:21 468422 PM", "level": "INFO", "func_name": "__step", "lineno": 233, "filename": "tasks.py", "msg": {"msg": "Entered self.__step", "method_signature": "__step(self, exc = None)", "vars": {"task_name": "ASYNC-Custom-task-Task-1", "exc": "None", "sent_from": "'_wakeup._else'"}}}
{"datetime": "2025-07-30 08:09:21 468422 PM", "level": "INFO", "func_name": "__step", "lineno": 243, "filename": "tasks.py", "msg": {"msg": "will initalized self._fut_waiter value", "vars": {"task_name": "ASYNC-Custom-task-Task-1"}}}
{"datetime": "2025-07-30 08:09:21 468422 PM", "level": "INFO", "func_name": "__step", "lineno": 245, "filename": "tasks.py", "msg": {"msg": "initalized self._fut_waiter to None", "vars": {"task_name": "ASYNC-Custom-task-Task-1"}}}
{"datetime": "2025-07-30 08:09:21 468422 PM", "level": "INFO", "func_name": "__step", "lineno": 250, "filename": "tasks.py", "msg": {"msg": "`try` of try-finally in `self.__step`. Call to __step_run_and_handle_request in next line.", "vars": {"task_name": "ASYNC-Custom-task-Task-1"}}}
{"datetime": "2025-07-30 08:09:21 468422 PM", "level": "INFO", "func_name": "__step_run_and_handle_result", "lineno": 264, "filename": "tasks.py", "msg": {"msg": "__step_run_and_handle_request entered", "method_signature": "__step_run_and_handle_result(self, exc)", "vars": {"task_name": "ASYNC-Custom-task-Task-1", "exc": "None"}}}
{"datetime": "2025-07-30 08:09:21 468422 PM", "level": "INFO", "func_name": "__step_run_and_handle_result", "lineno": 271, "filename": "tasks.py", "msg": {"msg": "`__step_run_and_hanle_result` main try-except exc is None so `coro.send()` in next line.", "vars": {"task_name": "ASYNC-Custom-task-Task-1"}}}
{"datetime": "2025-07-30 08:09:21 468422 PM", "level": "INFO", "func_name": "first", "lineno": 13, "filename": "understanding_tasks.py", "msg": "========= FIRST.SECOND Will sleep next for .3 seconds========================="}
{"datetime": "2025-07-30 08:09:21 468422 PM", "level": "INFO", "func_name": "__step_run_and_handle_result", "lineno": 274, "filename": "tasks.py", "msg": {"msg:": "__step_run_and_handle_result main try-except after `coro.send()`", "vars": {"task_name": "ASYNC-Custom-task-Task-1"}}}
{"datetime": "2025-07-30 08:09:21 468422 PM", "level": "INFO", "func_name": "__step_run_and_handle_result", "lineno": 312, "filename": "tasks.py", "msg": {"msg": "try-else in __step_run_and_handle_result", "vars": {"task_name": "ASYNC-Custom-task-Task-1", "future_name": "ASYNC-Custom-task-Task-1: name: 2", "result": "<Future pending created at C:\\Users\\shaik\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\asyncio\\base_events.py:448>", "is_asyncio_future_blocking": "getattr(result,\"_asyncio_future_blocking\", None)= True"}}}
{"datetime": "2025-07-30 08:09:21 468422 PM", "level": "INFO", "func_name": "__step_run_and_handle_result", "lineno": 315, "filename": "tasks.py", "msg": {"msg": "is_future blocking", "vars": {"task_name": "ASYNC-Custom-task-Task-1", "future_name": "ASYNC-Custom-task-Task-1: name: 2", "is_future_blocking": true}}}
{"datetime": "2025-07-30 08:09:21 468422 PM", "level": "INFO", "func_name": "__step_run_and_handle_result", "lineno": 332, "filename": "tasks.py", "msg": {"msg": "scheduling on EVENT_LOOP callback to fututre.add_done_call_back", "vars": {"task_name": "ASYNC-Custom-task-Task-1", "future_name": "ASYNC-Custom-task-Task-1: name: 2", "future_state": "PENDING", "result": "<Future pending created at C:\\Users\\shaik\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\asyncio\\base_events.py:448>", "scheduler_type": "call_soon"}}}
{"datetime": "2025-07-30 08:09:21 468422 PM", "level": "INFO", "func_name": "__step_run_and_handle_result", "lineno": 337, "filename": "tasks.py", "msg": {"msg": "After scheduling callbacks to fut. self._future_wait = result", "vars": {"task_name": "ASYNC-Custom-task-Task-1", "future_name": "ASYNC-Custom-task-Task-1: name: 2", "result": "<Future pending cb=[Task.__wakeup()] created at C:\\Users\\shaik\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\asyncio\\base_events.py:448>", "self._fut_waiter": null, "future_state": "PENDING", "future_callbacks_list(fut._callbacks)": [["__wakeup", "method"]]}}}
{"datetime": "2025-07-30 08:09:21 468422 PM", "level": "INFO", "func_name": "__step_run_and_handle_result", "lineno": 343, "filename": "tasks.py", "msg": {"msg": "self._fut_waiter set to result", "vars": {"task_name": "ASYNC-Custom-task-Task-1", "future_name": "ASYNC-Custom-task-Task-1: name: 2", "future_state": "PENDING", "self._fut_waiter": "<Future pending cb=[Task.__wakeup()] created at C:\\Users\\shaik\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\asyncio\\base_events.py:448>"}}}
{"datetime": "2025-07-30 08:09:21 468422 PM", "level": "INFO", "func_name": "__step_run_and_handle_result", "lineno": 376, "filename": "tasks.py", "msg": {"msg": "self finally set to None", "vars": {"task_name": "ASYNC-Custom-task-Task-1"}}}
{"datetime": "2025-07-30 08:09:21 468422 PM", "level": "INFO", "func_name": "__step", "lineno": 252, "filename": "tasks.py", "msg": {"msg": "`try` of try-finally in `self.__step`. After __step_run_and_handle_result", "vars": {"task_name": "ASYNC-Custom-task-Task-1"}}}
{"datetime": "2025-07-30 08:09:21 468422 PM", "level": "INFO", "func_name": "__step", "lineno": 257, "filename": "tasks.py", "msg": {"msg": "`finally` of try-finally in `self.__step`. Call to _leave_task next and then set self to None", "vars": {"task_name": "ASYNC-Custom-task-Task-1"}}}
{"datetime": "2025-07-30 08:09:21 484120 PM", "level": "INFO", "func_name": "__step", "lineno": 261, "filename": "tasks.py", "msg": {"msg": "`finally` of try-finally in `self.__step`.ASYNC-Custom-task-Task-1 set to none", "vars": {"task_name": "ASYNC-Custom-task-Task-1"}}}
{"datetime": "2025-07-30 08:09:21 484120 PM", "level": "INFO", "func_name": "__wakeup", "lineno": 405, "filename": "tasks.py", "msg": {"msg": "end of __wakeup. set self = None", "vars": {"task_name": "ASYNC-Custom-task-Task-1", "future_name": "ASYNC-Custom-task-Task-1: name: 1"}}}
{"datetime": "2025-07-30 08:09:21 774188 PM", "level": "INFO", "func_name": "__wakeup", "lineno": 381, "filename": "tasks.py", "msg": {"msg": "__wakeup entered", "vars": {"task_name": "ASYNC-Custom-task-Task-1", "future_name": "ASYNC-Custom-task-Task-1: name: 2", "future_state": "FINISHED"}}}
{"datetime": "2025-07-30 08:09:21 774188 PM", "level": "INFO", "func_name": "__wakeup", "lineno": 384, "filename": "tasks.py", "msg": {"msg": "will call future.result()", "vars": {"task_name": "ASYNC-Custom-task-Task-1", "future_name": "ASYNC-Custom-task-Task-1: name: 2"}}}
{"datetime": "2025-07-30 08:09:21 774188 PM", "level": "INFO", "func_name": "__wakeup", "lineno": 386, "filename": "tasks.py", "msg": {"msg": "__wakeup after future.result()", "vars": {"task_name": "ASYNC-Custom-task-Task-1", "future_name": "ASYNC-Custom-task-Task-1: name: 2", "future._state": "FINISHED"}}}
{"datetime": "2025-07-30 08:09:21 774188 PM", "level": "INFO", "func_name": "__wakeup", "lineno": 402, "filename": "tasks.py", "msg": {"msg": "__wakeup faced no exception when it called future.result()(ASYNC-Custom-task-Task-1: name: 2). calling again __step with no exc. I guess StopIteration will be raised", "vars": {"task_name": "ASYNC-Custom-task-Task-1", "future_name": "ASYNC-Custom-task-Task-1: name: 2"}}}
{"datetime": "2025-07-30 08:09:21 774188 PM", "level": "INFO", "func_name": "__step", "lineno": 233, "filename": "tasks.py", "msg": {"msg": "Entered self.__step", "method_signature": "__step(self, exc = None)", "vars": {"task_name": "ASYNC-Custom-task-Task-1", "exc": "None", "sent_from": "'_wakeup._else'"}}}
{"datetime": "2025-07-30 08:09:21 774188 PM", "level": "INFO", "func_name": "__step", "lineno": 243, "filename": "tasks.py", "msg": {"msg": "will initalized self._fut_waiter value", "vars": {"task_name": "ASYNC-Custom-task-Task-1"}}}
{"datetime": "2025-07-30 08:09:21 774188 PM", "level": "INFO", "func_name": "__step", "lineno": 245, "filename": "tasks.py", "msg": {"msg": "initalized self._fut_waiter to None", "vars": {"task_name": "ASYNC-Custom-task-Task-1"}}}
{"datetime": "2025-07-30 08:09:21 774188 PM", "level": "INFO", "func_name": "__step", "lineno": 250, "filename": "tasks.py", "msg": {"msg": "`try` of try-finally in `self.__step`. Call to __step_run_and_handle_request in next line.", "vars": {"task_name": "ASYNC-Custom-task-Task-1"}}}
{"datetime": "2025-07-30 08:09:21 774188 PM", "level": "INFO", "func_name": "__step_run_and_handle_result", "lineno": 264, "filename": "tasks.py", "msg": {"msg": "__step_run_and_handle_request entered", "method_signature": "__step_run_and_handle_result(self, exc)", "vars": {"task_name": "ASYNC-Custom-task-Task-1", "exc": "None"}}}
{"datetime": "2025-07-30 08:09:21 774188 PM", "level": "INFO", "func_name": "__step_run_and_handle_result", "lineno": 271, "filename": "tasks.py", "msg": {"msg": "`__step_run_and_hanle_result` main try-except exc is None so `coro.send()` in next line.", "vars": {"task_name": "ASYNC-Custom-task-Task-1"}}}
{"datetime": "2025-07-30 08:09:21 774188 PM", "level": "INFO", "func_name": "first", "lineno": 15, "filename": "understanding_tasks.py", "msg": "=========================== FIRST.THIRD No sleep================="}
{"datetime": "2025-07-30 08:09:21 774188 PM", "level": "INFO", "func_name": "first", "lineno": 17, "filename": "understanding_tasks.py", "msg": "========== END ==========="}
{"datetime": "2025-07-30 08:09:21 774188 PM", "level": "INFO", "func_name": "__step_run_and_handle_result", "lineno": 284, "filename": "tasks.py", "msg": {"msg": "StopIteration exception encountered.", "vars": {"task_name": "ASYNC-Custom-task-Task-1", "future_name": "NO_AWAITABLE"}}}
{"datetime": "2025-07-30 08:09:21 774188 PM", "level": "INFO", "func_name": "__step_run_and_handle_result", "lineno": 293, "filename": "tasks.py", "msg": {"msg": "__step_run_and_handle_result StopIteration encountered but the task is not cancelled.", "vars": {"task_name": "ASYNC-Custom-task-Task-1", "exc.value": "None"}}}
{"datetime": "2025-07-30 08:09:21 774188 PM", "level": "INFO", "func_name": "__step_run_and_handle_result", "lineno": 296, "filename": "tasks.py", "msg": {"msg": "super().set_result(exc.value)", "vars": {"task_name": "ASYNC-Custom-task-Task-1"}}}
{"datetime": "2025-07-30 08:09:21 774188 PM", "level": "INFO", "func_name": "__step_run_and_handle_result", "lineno": 376, "filename": "tasks.py", "msg": {"msg": "self finally set to None", "vars": {"task_name": "ASYNC-Custom-task-Task-1"}}}
{"datetime": "2025-07-30 08:09:21 774188 PM", "level": "INFO", "func_name": "__step", "lineno": 252, "filename": "tasks.py", "msg": {"msg": "`try` of try-finally in `self.__step`. After __step_run_and_handle_result", "vars": {"task_name": "ASYNC-Custom-task-Task-1"}}}
{"datetime": "2025-07-30 08:09:21 774188 PM", "level": "INFO", "func_name": "__step", "lineno": 257, "filename": "tasks.py", "msg": {"msg": "`finally` of try-finally in `self.__step`. Call to _leave_task next and then set self to None", "vars": {"task_name": "ASYNC-Custom-task-Task-1"}}}
{"datetime": "2025-07-30 08:09:21 774188 PM", "level": "INFO", "func_name": "__step", "lineno": 261, "filename": "tasks.py", "msg": {"msg": "`finally` of try-finally in `self.__step`.ASYNC-Custom-task-Task-1 set to none", "vars": {"task_name": "ASYNC-Custom-task-Task-1"}}}
{"datetime": "2025-07-30 08:09:21 774188 PM", "level": "INFO", "func_name": "__wakeup", "lineno": 405, "filename": "tasks.py", "msg": {"msg": "end of __wakeup. set self = None", "vars": {"task_name": "ASYNC-Custom-task-Task-1", "future_name": "ASYNC-Custom-task-Task-1: name: 2"}}}
{"datetime": "2025-07-30 08:09:21 789867 PM", "level": "INFO", "func_name": "task_factory", "lineno": 412, "filename": "tasks.py", "msg": {"msg": "initalizing task", "vars": {"loop": "<ProactorEventLoop running=False closed=False debug=True>", "coro": "<coroutine object BaseEventLoop.shutdown_asyncgens at 0x000001CC14FF4BF0>", "task_name": "ASYNC-Custom-task-Task-3"}}}
{"datetime": "2025-07-30 08:09:21 789867 PM", "level": "INFO", "func_name": "__init__", "lineno": 48, "filename": "tasks.py", "msg": {"msg": "__init__ initalized"}}
{"datetime": "2025-07-30 08:09:21 789867 PM", "level": "INFO", "func_name": "__init__", "lineno": 76, "filename": "tasks.py", "msg": {"msg": "self.__step scheduled on EVENT_LOOP in __init__", "vars": {"task_name": "ASYNC-Custom-task-Task-3", "scheduler_type": "call_soon"}}}
{"datetime": "2025-07-30 08:09:21 789867 PM", "level": "INFO", "func_name": "__init__", "lineno": 79, "filename": "tasks.py", "msg": {"msg": "__init__ after scheduling __step on EVENT_LOOP using loop.call_soon", "vars": {"task_name": "ASYNC-Custom-task-Task-3", "scheduler_type": "call_soon"}}}
{"datetime": "2025-07-30 08:09:21 792966 PM", "level": "INFO", "func_name": "__step", "lineno": 233, "filename": "tasks.py", "msg": {"msg": "Entered self.__step", "method_signature": "__step(self, exc = None)", "vars": {"task_name": "ASYNC-Custom-task-Task-3", "exc": "None", "sent_from": "'__init__'"}}}
{"datetime": "2025-07-30 08:09:21 792966 PM", "level": "INFO", "func_name": "__step", "lineno": 243, "filename": "tasks.py", "msg": {"msg": "will initalized self._fut_waiter value", "vars": {"task_name": "ASYNC-Custom-task-Task-3"}}}
{"datetime": "2025-07-30 08:09:21 792966 PM", "level": "INFO", "func_name": "__step", "lineno": 245, "filename": "tasks.py", "msg": {"msg": "initalized self._fut_waiter to None", "vars": {"task_name": "ASYNC-Custom-task-Task-3"}}}
{"datetime": "2025-07-30 08:09:21 792966 PM", "level": "INFO", "func_name": "__step", "lineno": 250, "filename": "tasks.py", "msg": {"msg": "`try` of try-finally in `self.__step`. Call to __step_run_and_handle_request in next line.", "vars": {"task_name": "ASYNC-Custom-task-Task-3"}}}
{"datetime": "2025-07-30 08:09:21 792966 PM", "level": "INFO", "func_name": "__step_run_and_handle_result", "lineno": 264, "filename": "tasks.py", "msg": {"msg": "__step_run_and_handle_request entered", "method_signature": "__step_run_and_handle_result(self, exc)", "vars": {"task_name": "ASYNC-Custom-task-Task-3", "exc": "None"}}}
{"datetime": "2025-07-30 08:09:21 792966 PM", "level": "INFO", "func_name": "__step_run_and_handle_result", "lineno": 271, "filename": "tasks.py", "msg": {"msg": "`__step_run_and_hanle_result` main try-except exc is None so `coro.send()` in next line.", "vars": {"task_name": "ASYNC-Custom-task-Task-3"}}}
{"datetime": "2025-07-30 08:09:21 792966 PM", "level": "INFO", "func_name": "__step_run_and_handle_result", "lineno": 284, "filename": "tasks.py", "msg": {"msg": "StopIteration exception encountered.", "vars": {"task_name": "ASYNC-Custom-task-Task-3", "future_name": "NO_AWAITABLE"}}}
{"datetime": "2025-07-30 08:09:21 792966 PM", "level": "INFO", "func_name": "__step_run_and_handle_result", "lineno": 293, "filename": "tasks.py", "msg": {"msg": "__step_run_and_handle_result StopIteration encountered but the task is not cancelled.", "vars": {"task_name": "ASYNC-Custom-task-Task-3", "exc.value": "None"}}}
{"datetime": "2025-07-30 08:09:21 792966 PM", "level": "INFO", "func_name": "__step_run_and_handle_result", "lineno": 296, "filename": "tasks.py", "msg": {"msg": "super().set_result(exc.value)", "vars": {"task_name": "ASYNC-Custom-task-Task-3"}}}
{"datetime": "2025-07-30 08:09:21 792966 PM", "level": "INFO", "func_name": "__step_run_and_handle_result", "lineno": 376, "filename": "tasks.py", "msg": {"msg": "self finally set to None", "vars": {"task_name": "ASYNC-Custom-task-Task-3"}}}
{"datetime": "2025-07-30 08:09:21 792966 PM", "level": "INFO", "func_name": "__step", "lineno": 252, "filename": "tasks.py", "msg": {"msg": "`try` of try-finally in `self.__step`. After __step_run_and_handle_result", "vars": {"task_name": "ASYNC-Custom-task-Task-3"}}}
{"datetime": "2025-07-30 08:09:21 792966 PM", "level": "INFO", "func_name": "__step", "lineno": 257, "filename": "tasks.py", "msg": {"msg": "`finally` of try-finally in `self.__step`. Call to _leave_task next and then set self to None", "vars": {"task_name": "ASYNC-Custom-task-Task-3"}}}
{"datetime": "2025-07-30 08:09:21 792966 PM", "level": "INFO", "func_name": "__step", "lineno": 261, "filename": "tasks.py", "msg": {"msg": "`finally` of try-finally in `self.__step`.ASYNC-Custom-task-Task-3 set to none", "vars": {"task_name": "ASYNC-Custom-task-Task-3"}}}
{"datetime": "2025-07-30 08:09:21 792966 PM", "level": "INFO", "func_name": "task_factory", "lineno": 412, "filename": "tasks.py", "msg": {"msg": "initalizing task", "vars": {"loop": "<ProactorEventLoop running=False closed=False debug=True>", "coro": "<coroutine object BaseEventLoop.shutdown_default_executor at 0x000001CC14F7A2F0>", "task_name": "ASYNC-Custom-task-Task-4"}}}
{"datetime": "2025-07-30 08:09:21 792966 PM", "level": "INFO", "func_name": "__init__", "lineno": 48, "filename": "tasks.py", "msg": {"msg": "__init__ initalized"}}
{"datetime": "2025-07-30 08:09:21 792966 PM", "level": "INFO", "func_name": "__init__", "lineno": 76, "filename": "tasks.py", "msg": {"msg": "self.__step scheduled on EVENT_LOOP in __init__", "vars": {"task_name": "ASYNC-Custom-task-Task-4", "scheduler_type": "call_soon"}}}
{"datetime": "2025-07-30 08:09:21 792966 PM", "level": "INFO", "func_name": "__init__", "lineno": 79, "filename": "tasks.py", "msg": {"msg": "__init__ after scheduling __step on EVENT_LOOP using loop.call_soon", "vars": {"task_name": "ASYNC-Custom-task-Task-4", "scheduler_type": "call_soon"}}}
{"datetime": "2025-07-30 08:09:21 792966 PM", "level": "INFO", "func_name": "__step", "lineno": 233, "filename": "tasks.py", "msg": {"msg": "Entered self.__step", "method_signature": "__step(self, exc = None)", "vars": {"task_name": "ASYNC-Custom-task-Task-4", "exc": "None", "sent_from": "'__init__'"}}}
{"datetime": "2025-07-30 08:09:21 792966 PM", "level": "INFO", "func_name": "__step", "lineno": 243, "filename": "tasks.py", "msg": {"msg": "will initalized self._fut_waiter value", "vars": {"task_name": "ASYNC-Custom-task-Task-4"}}}
{"datetime": "2025-07-30 08:09:21 792966 PM", "level": "INFO", "func_name": "__step", "lineno": 245, "filename": "tasks.py", "msg": {"msg": "initalized self._fut_waiter to None", "vars": {"task_name": "ASYNC-Custom-task-Task-4"}}}
{"datetime": "2025-07-30 08:09:21 792966 PM", "level": "INFO", "func_name": "__step", "lineno": 250, "filename": "tasks.py", "msg": {"msg": "`try` of try-finally in `self.__step`. Call to __step_run_and_handle_request in next line.", "vars": {"task_name": "ASYNC-Custom-task-Task-4"}}}
{"datetime": "2025-07-30 08:09:21 792966 PM", "level": "INFO", "func_name": "__step_run_and_handle_result", "lineno": 264, "filename": "tasks.py", "msg": {"msg": "__step_run_and_handle_request entered", "method_signature": "__step_run_and_handle_result(self, exc)", "vars": {"task_name": "ASYNC-Custom-task-Task-4", "exc": "None"}}}
{"datetime": "2025-07-30 08:09:21 792966 PM", "level": "INFO", "func_name": "__step_run_and_handle_result", "lineno": 271, "filename": "tasks.py", "msg": {"msg": "`__step_run_and_hanle_result` main try-except exc is None so `coro.send()` in next line.", "vars": {"task_name": "ASYNC-Custom-task-Task-4"}}}
{"datetime": "2025-07-30 08:09:21 792966 PM", "level": "INFO", "func_name": "__step_run_and_handle_result", "lineno": 284, "filename": "tasks.py", "msg": {"msg": "StopIteration exception encountered.", "vars": {"task_name": "ASYNC-Custom-task-Task-4", "future_name": "NO_AWAITABLE"}}}
{"datetime": "2025-07-30 08:09:21 792966 PM", "level": "INFO", "func_name": "__step_run_and_handle_result", "lineno": 293, "filename": "tasks.py", "msg": {"msg": "__step_run_and_handle_result StopIteration encountered but the task is not cancelled.", "vars": {"task_name": "ASYNC-Custom-task-Task-4", "exc.value": "None"}}}
{"datetime": "2025-07-30 08:09:21 792966 PM", "level": "INFO", "func_name": "__step_run_and_handle_result", "lineno": 296, "filename": "tasks.py", "msg": {"msg": "super().set_result(exc.value)", "vars": {"task_name": "ASYNC-Custom-task-Task-4"}}}
{"datetime": "2025-07-30 08:09:21 805752 PM", "level": "INFO", "func_name": "__step_run_and_handle_result", "lineno": 376, "filename": "tasks.py", "msg": {"msg": "self finally set to None", "vars": {"task_name": "ASYNC-Custom-task-Task-4"}}}
{"datetime": "2025-07-30 08:09:21 805752 PM", "level": "INFO", "func_name": "__step", "lineno": 252, "filename": "tasks.py", "msg": {"msg": "`try` of try-finally in `self.__step`. After __step_run_and_handle_result", "vars": {"task_name": "ASYNC-Custom-task-Task-4"}}}
{"datetime": "2025-07-30 08:09:21 805752 PM", "level": "INFO", "func_name": "__step", "lineno": 257, "filename": "tasks.py", "msg": {"msg": "`finally` of try-finally in `self.__step`. Call to _leave_task next and then set self to None", "vars": {"task_name": "ASYNC-Custom-task-Task-4"}}}
{"datetime": "2025-07-30 08:09:21 805752 PM", "level": "INFO", "func_name": "__step", "lineno": 261, "filename": "tasks.py", "msg": {"msg": "`finally` of try-finally in `self.__step`.ASYNC-Custom-task-Task-4 set to none", "vars": {"task_name": "ASYNC-Custom-task-Task-4"}}}
